In [1]:
import numpy as np
import pandas as pd

In [2]:
forum_users = {
    'User ID': np.array([1, 2, 3, 4, 5]),
    'Username': ['bogdan_s', 'matvii', 'lexa134', 'svetlana1978', 'yaroslav2000'],
    'Age': [17, 15, 15, 48, None],
    'Joined Date': pd.to_datetime(['2032-01-01', '2026-10-10', '2024-05-09', '2020-11-10', '2019-12-01',]),
    'Total Posts': [20, 50, 123, 949, 322],
    'Reputation': [500, 800, 312, 999, 999],
}

df = pd.DataFrame(forum_users)
df

   User ID      Username   Age Joined Date  Total Posts  Reputation
0        1      bogdan_s  17.0  2032-01-01           20         500
1        2        matvii  15.0  2026-10-10           50         800
2        3       lexa134  15.0  2024-05-09          123         312
3        4  svetlana1978  48.0  2020-11-10          949         999
4        5  yaroslav2000   NaN  2019-12-01          322         999

In [3]:
df[['Username', 'Age']] # Get only specific columns

       Username   Age
0      bogdan_s  17.0
1        matvii  15.0
2       lexa134  15.0
3  svetlana1978  48.0
4  yaroslav2000   NaN

In [4]:
df.loc[3] # Get a series of a specific row (index 3)

User ID                          4
Username              svetlana1978
Age                           48.0
Joined Date    2020-11-10 00:00:00
Total Posts                    949
Reputation                     999
Name: 3, dtype: object

In [5]:
df.loc[2:3] # Get two series of two specific rows

   User ID      Username   Age Joined Date  Total Posts  Reputation
2        3       lexa134  15.0  2024-05-09          123         312
3        4  svetlana1978  48.0  2020-11-10          949         999

In [6]:
df.loc[2:3, ['Username', 'Joined Date', 'Reputation']] # Get two rows and specific columns

       Username Joined Date  Reputation
2       lexa134  2024-05-09         312
3  svetlana1978  2020-11-10         999

In [7]:
df.iloc[3] # The same as loc

User ID                          4
Username              svetlana1978
Age                           48.0
Joined Date    2020-11-10 00:00:00
Total Posts                    949
Reputation                     999
Name: 3, dtype: object

In [13]:
df.iloc[2:4] # 4 is not included

RangeIndex(start=0, stop=5, step=1)

In [10]:
df.iloc[2:4, 1:4] # 1:4 means indexes of columns (4 is not included)

       Username   Age Joined Date
2       lexa134  15.0  2024-05-09
3  svetlana1978  48.0  2020-11-10

In [14]:
df.iloc[:, 1:4] # 1:4 means indexes of columns (4 is not included) : means everything

       Username   Age Joined Date
0      bogdan_s  17.0  2032-01-01
1        matvii  15.0  2026-10-10
2       lexa134  15.0  2024-05-09
3  svetlana1978  48.0  2020-11-10
4  yaroslav2000   NaN  2019-12-01

In [15]:
df[df['Age'] >= 25] # Filter original DataFrame

   User ID      Username   Age Joined Date  Total Posts  Reputation
3        4  svetlana1978  48.0  2020-11-10          949         999

In [16]:
df['Age'] >= 25 # Get a series

0    False
1    False
2    False
3     True
4    False
Name: Age, dtype: bool

In [20]:
df[df['Reputation'] == 999]

   User ID      Username   Age Joined Date  Total Posts  Reputation
3        4  svetlana1978  48.0  2020-11-10          949         999
4        5  yaroslav2000   NaN  2019-12-01          322         999

In [22]:
df[(df['Total Posts'] >= 300) & (df['Age'] >= 25)] # & means "and"

   User ID      Username   Age Joined Date  Total Posts  Reputation
3        4  svetlana1978  48.0  2020-11-10          949         999

In [25]:
df[(df['Total Posts'] >= 200) | (df['Age'] <= 15)] # | means "or"

   User ID      Username   Age Joined Date  Total Posts  Reputation
1        2        matvii  15.0  2026-10-10           50         800
2        3       lexa134  15.0  2024-05-09          123         312
3        4  svetlana1978  48.0  2020-11-10          949         999
4        5  yaroslav2000   NaN  2019-12-01          322         999

In [28]:
df['Reputation'].isin([200, 500]) # or 200 or 500

0    False
1    False
2    False
3    False
4    False
Name: Reputation, dtype: bool

In [29]:
df[df['Reputation'].isin([200, 500])]

   User ID  Username   Age Joined Date  Total Posts  Reputation
0        1  bogdan_s  17.0  2032-01-01           20         500

In [33]:
df[df['Reputation'].isin(range(100, 800))] # from 100 (included) to 800 (not included)

   User ID  Username   Age Joined Date  Total Posts  Reputation
0        1  bogdan_s  17.0  2032-01-01           20         500
2        3   lexa134  15.0  2024-05-09          123         312

In [42]:
date_range = pd.date_range(start='2021-03-01', end='2032-08-01') # freq='D' means Days
date_range

DatetimeIndex(['2021-03-01', '2021-03-02', '2021-03-03', '2021-03-04',
               '2021-03-05', '2021-03-06', '2021-03-07', '2021-03-08',
               '2021-03-09', '2021-03-10',
               ...
               '2032-07-23', '2032-07-24', '2032-07-25', '2032-07-26',
               '2032-07-27', '2032-07-28', '2032-07-29', '2032-07-30',
               '2032-07-31', '2032-08-01'],
              dtype='datetime64[us]', length=4172, freq='D')

In [41]:
df[df['Joined Date'].isin(date_range)]

   User ID      Username   Age Joined Date  Total Posts  Reputation
0        1      bogdan_s  17.0  2032-01-01           20         500
1        2        matvii  15.0  2026-10-10           50         800
2        3       lexa134  15.0  2024-05-09          123         312
3        4  svetlana1978  48.0  2020-11-10          949         999
4        5  yaroslav2000   NaN  2019-12-01          322         999