In [1]:
import numpy as np
import pandas as pd

In [2]:
forum_users = {
    'User ID': np.array([1, 2, 3, 4, 5]),
    'Username': ['bogdan_s', 'matvii', 'lexa134', 'svetlana1978', 'yaroslav2000'],
    'Age': [17, 15, 15, 48, None],
    'Joined Date': pd.to_datetime(['2032-01-01', '2026-10-10', '2024-05-09', '2020-11-10', '2019-12-01',]),
    'Total Posts': [20, 50, 123, 949, 322],
    'Reputation': [500, 800, 312, 999, 999],
}

df = pd.DataFrame(forum_users)
df

   User ID      Username   Age Joined Date  Total Posts  Reputation
0        1      bogdan_s  17.0  2032-01-01           20         500
1        2        matvii  15.0  2026-10-10           50         800
2        3       lexa134  15.0  2024-05-09          123         312
3        4  svetlana1978  48.0  2020-11-10          949         999
4        5  yaroslav2000   NaN  2019-12-01          322         999

In [36]:
# Adding new column
df['Language'] = 'English'
df

,User ID,Username,Age,Joined Date,Total Posts,Reputation,Active,Total Comments,Language
0,1,bogdan_s,17.0,English,20,100,True,70,English
1,2,matvii,15.0,English,50,300,False,30,English
2,3,lexa134,15.0,English,123,200,False,50,English
3,4,svetlana1978,48.0,English,949,100,True,45,English
4,5,yaroslav2000,NaN,English,322,500,True,80,English

In [12]:
# Change values
df['Reputation'] = [100, 300, 200, 100, 500] # The order!!
df

   User ID      Username   Age Joined Date  Total Posts  Reputation Language
0        1      bogdan_s  17.0     English           20         100  English
1        2        matvii  15.0     English           50         300  English
2        3       lexa134  15.0     English          123         200  English
3        4  svetlana1978  48.0     English          949         100  English
4        5  yaroslav2000   NaN     English          322         500  English

In [16]:
df['Active'] = np.array([True, False, False, True, True]) # The same as the lsit
df

,User ID,Username,Age,Joined Date,Total Posts,Reputation,Language,Active
0,1,bogdan_s,17.0,English,20,100,English,True
1,2,matvii,15.0,English,50,300,English,False
2,3,lexa134,15.0,English,123,200,English,False
3,4,svetlana1978,48.0,English,949,100,English,True
4,5,yaroslav2000,NaN,English,322,500,English,True

In [26]:
total_comments = {
    'Total Comments': [70, 30, 50, 45, 80]
}
# df2 = pd.DataFrame(total_comments, index=['a', 'b', 'c', 'd', 'e']) # You can also change index
df2 = pd.DataFrame(total_comments)
df2

   Total Comments
0              70
1              30
2              50
3              45
4              80

In [23]:
#By default concat works on axis 0!
pd.concat([df, df2])

,User ID,Username,Age,Joined Date,Total Posts,Reputation,Language,Active,Total Comments
0,1.0,bogdan_s,17.0,English,20.0,100.0,English,True,NaN
1,2.0,matvii,15.0,English,50.0,300.0,English,False,NaN
2,3.0,lexa134,15.0,English,123.0,200.0,English,False,NaN
3,4.0,svetlana1978,48.0,English,949.0,100.0,English,True,NaN
4,5.0,yaroslav2000,NaN,English,322.0,500.0,English,True,NaN
a,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,70.0
b,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30.0
c,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50.0
d,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,45.0
e,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,80.0

In [28]:
df = pd.concat([df, df2], axis=1)
df

,User ID,Username,Age,Joined Date,Total Posts,Reputation,Language,Active,Total Comments
0,1,bogdan_s,17.0,English,20,100,English,True,70
1,2,matvii,15.0,English,50,300,English,False,30
2,3,lexa134,15.0,English,123,200,English,False,50
3,4,svetlana1978,48.0,English,949,100,English,True,45
4,5,yaroslav2000,NaN,English,322,500,English,True,80

In [29]:
df.drop(['Language'], axis=1) # By default axis = 0! Original DataFrame wasn't changed!

,User ID,Username,Age,Joined Date,Total Posts,Reputation,Active,Total Comments
0,1,bogdan_s,17.0,English,20,100,True,70
1,2,matvii,15.0,English,50,300,False,30
2,3,lexa134,15.0,English,123,200,False,50
3,4,svetlana1978,48.0,English,949,100,True,45
4,5,yaroslav2000,NaN,English,322,500,True,80

In [37]:
df.drop(['Language'], axis=1, inplace=True) # Will change original DataFrame!
df

,User ID,Username,Age,Joined Date,Total Posts,Reputation,Active,Total Comments
0,1,bogdan_s,17.0,English,20,100,True,70
1,2,matvii,15.0,English,50,300,False,30
2,3,lexa134,15.0,English,123,200,False,50
3,4,svetlana1978,48.0,English,949,100,True,45
4,5,yaroslav2000,NaN,English,322,500,True,80

In [38]:
df.drop([2, 3]) # Delete rows with indexes 2 and 3

,User ID,Username,Age,Joined Date,Total Posts,Reputation,Active,Total Comments
0,1,bogdan_s,17.0,English,20,100,True,70
1,2,matvii,15.0,English,50,300,False,30
4,5,yaroslav2000,NaN,English,322,500,True,80