In [3]:
import pandas as pd
import numpy as np

## Data Frames

In [4]:
forum_users = {
    'User ID': np.array([1, 2, 3, 4, 5]),
    'Username': ['bogdan_s', 'matvii', 'lexa134', 'svetlana1978', 'yaroslav2000'],
    'Age': [17, 15, 15, 48, None],
    'Joined Date': pd.to_datetime(['2032-01-01', '2026-10-10', '2024-05-09', '2020-11-10', '2019-12-01',]),
    'Total Posts': [20, 50, 123, 949, 322],
    'Reputation': [500, 800, 312, 999, 999],
}

df = pd.DataFrame(forum_users)
df

   User ID      Username   Age Joined Date  Total Posts  Reputation
0        1      bogdan_s  17.0  2032-01-01           20         500
1        2        matvii  15.0  2026-10-10           50         800
2        3       lexa134  15.0  2024-05-09          123         312
3        4  svetlana1978  48.0  2020-11-10          949         999
4        5  yaroslav2000   NaN  2019-12-01          322         999

In [40]:
df.shape

(5, 6)

In [41]:
type(df)

pandas.DataFrame

In [42]:
df.columns

Index(['User ID', 'Username', 'Age', 'Joined Date', 'Total Posts',
       'Reputation'],
      dtype='str')

In [43]:
type(df.columns)

pandas.Index

In [44]:
df.columns.tolist()

['User ID', 'Username', 'Age', 'Joined Date', 'Total Posts', 'Reputation']

In [45]:
df.index.tolist()

[0, 1, 2, 3, 4]

In [46]:
df.dtypes

User ID                 int64
Username                  str
Age                   float64
Joined Date    datetime64[us]
Total Posts             int64
Reputation              int64
dtype: object

In [47]:
df.values

array([[1, 'bogdan_s', 17.0, Timestamp('2032-01-01 00:00:00'), 20, 500],
       [2, 'matvii', 15.0, Timestamp('2026-10-10 00:00:00'), 50, 800],
       [3, 'lexa134', 15.0, Timestamp('2024-05-09 00:00:00'), 123, 312],
       [4, 'svetlana1978', 48.0, Timestamp('2020-11-10 00:00:00'), 949,
        999],
       [5, 'yaroslav2000', nan, Timestamp('2019-12-01 00:00:00'), 322,
        999]], dtype=object)

In [48]:
type(df.values)

numpy.ndarray

In [49]:
df.values[1, 1]

'matvii'

In [50]:
df.head(3) # doesn't change real df. Returns df

   User ID  Username   Age Joined Date  Total Posts  Reputation
0        1  bogdan_s  17.0  2032-01-01           20         500
1        2    matvii  15.0  2026-10-10           50         800
2        3   lexa134  15.0  2024-05-09          123         312

In [51]:
type(df.head(3))

pandas.DataFrame

In [52]:
df.tail(2) # last two rows

   User ID      Username   Age Joined Date  Total Posts  Reputation
3        4  svetlana1978  48.0  2020-11-10          949         999
4        5  yaroslav2000   NaN  2019-12-01          322         999

In [53]:
df.describe().round(2) # Returns a dataframe

       User ID    Age          Joined Date  Total Posts  Reputation
count     5.00   4.00                    5         5.00        5.00
mean      3.00  23.75  2024-10-12 00:00:00       292.80      722.00
min       1.00  15.00  2019-12-01 00:00:00        20.00      312.00
25%       2.00  15.00  2020-11-10 00:00:00        50.00      500.00
50%       3.00  16.00  2024-05-09 00:00:00       123.00      800.00
75%       4.00  24.75  2026-10-10 00:00:00       322.00      999.00
max       5.00  48.00  2032-01-01 00:00:00       949.00      999.00
std       1.58  16.19                  NaN       385.24      306.97

In [5]:
df.select_dtypes(include=['str', 'int64']) # You can also write exclude which means NOT IS

   User ID      Username  Total Posts  Reputation
0        1      bogdan_s           20         500
1        2        matvii           50         800
2        3       lexa134          123         312
3        4  svetlana1978          949         999
4        5  yaroslav2000          322         999

In [55]:
df.select_dtypes(include='str').columns.tolist()

['Username']

In [56]:
df.select_dtypes(include='int64')

   User ID  Total Posts  Reputation
0        1           20         500
1        2           50         800
2        3          123         312
3        4          949         999
4        5          322         999

In [57]:
df.isna() # isna means "is not available"

   User ID  Username    Age  Joined Date  Total Posts  Reputation
0    False     False  False        False        False       False
1    False     False  False        False        False       False
2    False     False  False        False        False       False
3    False     False  False        False        False       False
4    False     False   True        False        False       False

In [58]:
df.isna().sum() # Count all missing values

User ID        0
Username       0
Age            1
Joined Date    0
Total Posts    0
Reputation     0
dtype: int64